# Generated by Django 2.1.4 on 2019-08-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('main', 'MAIN'), ('side', 'SIDE')], default='main', max_length=6),
        ),
    ]
