# Generated by Django 2.1.4 on 2019-08-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('main', 'MAIN'), ('side', 'SIDE'), ('science', 'SCIENCE')], default='main', max_length=10),
        ),
    ]
