# Generated by Django 2.2.6 on 2019-10-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190830_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('business', 'Business'), ('politics', 'Politics'), ('real estate', 'Real Estate'), ('travel', 'Travel'), ('sports', 'Sports'), ('technology', 'Technology'), ('education', 'Education'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('art', 'Art'), ('short story', 'Short Story'), ('science', 'Science')], default='main', max_length=10),
        ),
    ]
