# Generated by Django 2.2.6 on 2019-10-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191017_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='paragraph10',
            field=models.TextField(blank=True, null=True),
        ),
    ]
