# Generated by Django 2.2.6 on 2019-10-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_detailed_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='detailed_caption',
            new_name='writer',
        ),
    ]
